### ISSUE TITLE
help I keep getting this error

### ISSUE THREAD

**Issue by Katzkaa** [Pilot1782/bad_copenheimer#10]
name = data["name"]
KeyError: 'name'

**Comment by Pilot1782** [comment]
Make sure in the settings.json file there is a setting called name with a value of something ie:

“name”:”pilot1782”

**Comment by PilaCiu** [comment]
The setting is not present, you need to add it yourself it seems.

**Comment by Katzkaa** [comment]
how do I add it? thank you in advance

**Comment by Pilot1782** [comment]
Go to 
https://raw.githubusercontent.com/Pilot1782/bad_copenheimer/main/settings.json
copy all the text into your settings file and reconfigure it to your needs

**Comment by Katzkaa** [comment]
ok it works fine now, thanks also whats the reccomended amount of threads? ty :D

**Comment by Pilot1782** [comment]
Threads can be whatever’s you want but to use your computer while it’s running and be efficient I recommend 1020 since it large enough and a multiple of 255

**Comment by Katzkaa** [comment]
Got it, thanks and great work, keep it up :^)
