### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CofNet** [Pilot1782/bad_copenheimer#107]
### What happened?

hi, whenever i try to send a command on the discord bot or i click the "Next server" button on discord when i do /find, it always says "interaction failed" do you know the problem? i'm using dev build 
![image](https://user-images.githubusercontent.com/108759805/214700137-750f0b7b-568d-4f95-b363-dba255ab403c.png)

### Operating Sys

Linux

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
THere was none
```

**Comment by CofNet** [comment]
wait, the code is:

Task exception was never retrieved
future: <Task finished name='Task-78' coro=<rand_select() done, defined at /home/foxon60fos/baddy/bad_copenheimer-dev-builds/mongoBot.pyw:234> exception=LibraryException('\n  Error 10062 | Unknown Interaction.:\n  Unknown interaction.\n  Severity 40.')>
Traceback (most recent call last):
  File "/home/foxon60fos/baddy/bad_copenheimer-dev-builds/mongoBot.pyw", line 236, in rand_select
    await ctx.defer(edit_origin=True)
  File "/usr/local/lib/python3.9/dist-packages/interactions/client/context.py", line 704, in defer
    await self._client.create_interaction_response(
  File "/usr/local/lib/python3.9/dist-packages/interactions/api/http/interaction.py", line 227, in create_interaction_response
    return await self._req.request(
  File "/usr/local/lib/python3.9/dist-packages/interactions/api/http/request.py", line 172, in request
    raise LibraryException(
interactions.api.error.LibraryException: 
  Error 10062 | Unknown Interaction.:
  Unknown interaction.
  Severity 40.
Duplicates removed

**Comment by CofNet** [comment]
also, is there a way to make scanCore.py go faster?

**Comment by Pilot1782** [comment]
As for the scanCore.py at the top of the file, you can edit the max threads via `maxActive = 5` and pings per second via `pingsPerSec = 2400`.

**Comment by Pilot1782** [comment]
I am unable to replicate you issue, but I suspect that it is due to you hitting to button too much, and 'spamming' the refresh, you should only hit it once and wait for it to update, which can take as long as 1-2min.
