### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by McMelonTV** [Pilot1782/bad_copenheimer#12]
![image](https://user-images.githubusercontent.com/62901799/150819720-69bd8e6c-2d6c-446f-ae39-b4866145727f.png)
![image](https://user-images.githubusercontent.com/62901799/150819727-d92f1528-bd89-4f94-9020-7cf47f73bd51.png)

**Comment by McMelonTV** [comment]
![image](https://user-images.githubusercontent.com/62901799/150820141-49ea469a-bdc3-4895-af1d-a7338fa4b129.png)

**Comment by McMelonTV** [comment]
![image](https://user-images.githubusercontent.com/62901799/150825991-53128a80-f70a-4f91-a912-4f2679a50805.png)
nope

**Comment by McMelonTV** [comment]
![image](https://user-images.githubusercontent.com/62901799/150826049-0770a245-2516-4251-9945-a65d4f674ba0.png)

**Comment by Pilot1782** [comment]
The new push fixed status but I will need to look into !mc more to fix it.

**Comment by Pilot1782** [comment]
!mc is fixed

**Comment by McMelonTV** [comment]
![image](https://user-images.githubusercontent.com/62901799/150846212-49aef0b9-2b77-45a7-9478-77980a3ca7b6.png)

**Comment by Pilot1782** [comment]
Install java with [This Guide](https://java.com/en/download/help/linux_x64_install.html).
