### ISSUE TITLE
[Bug]: Scanning terminated after 4 ips

### ISSUE THREAD

**Issue by McMelonTV** [Pilot1782/bad_copenheimer#14]
### Contact Details

McMelon#9999 on Discord

### What happened?

A bug happened!

![image](https://user-images.githubusercontent.com/62901799/151048155-96d7de4b-310e-4867-944d-7fa9556fc18d.png)

### Version

1.7 (Default)

### Relevant log output

```shell
Scanning 172.65.238.0-172.65.240.255 outputting False
   ____        _           _____

  / __ \      | |         / ____|

 | |  | |_   _| |__   ___| (___   ___ __ _ _ __  _ __   ___ _ __

 | |  | | | | | '_ \ / _ \\___ \ / __/ _` | '_ \| '_ \ / _ \ '__|

 | |__| | |_| | |_) | (_) |___) | (_| (_| | | | | | | |  __/ |

  \___\_\\__,_|_.__/ \___/_____/ \___\__,_|_| |_|_| |_|\___|_|



By @replydev on Telegram

Version 0.3.7

[19:43:04] - Skipping the initial ping due to the few ports inserted

[19:43:04] - Checking Servers...

(172.65.238.110:25565)(32/1234)(RelightProxy - 1.18.x)()

(172.65.239.18:25565)(13/2000)(Velocity 1.8-1.18.1)(Lucky Network [1.8 - 1.17])

(172.65.240.39:25565)(0/0)(§cClosed Beta Network)(NeruxVace Network Closed Beta Network)

(172.65.240.147:25565)(0/0)(TCPShield.com)(Invalid hostname. Please refer to our documentation at docs.tcpshield.com)

[19:43:13] - Scan time: 8 seconds

[19:43:13] - Scan terminated - 4 (4 in total)
```

**Comment by Pilot1782** [comment]
In the settings.json file change the ip range to the desired range as currently it is a a default testing range to make sure the bot is working.

**Comment by McMelonTV** [comment]
![image](https://user-images.githubusercontent.com/62901799/151060369-55ccf443-a9c4-4ae8-b4c1-20c6d986ab21.png)

**Comment by Pilot1782** [comment]
Does the program fully stop (the program exits), hang (it freezes) or fail (shows an error) after the test scan?

**Comment by McMelonTV** [comment]
it just hangs

**Comment by Pilot1782** [comment]
When the program hangs, does it still respond to other commands such as !help?

**Comment by McMelonTV** [comment]
I'm not sure at the moment, I'll try tomorrow but I think it does

Dňa ut 25. 1. 2022, 23:02 pilot1782 ***@***.***> napísal(a):

**Comment by Pilot1782** [comment]
I'm having trouble with reproducing this, is there anything special you're doing?

**Comment by McMelonTV** [comment]
nope, nothing special

**Comment by Pilot1782** [comment]
Well, my best advice is to make a copy of your setting.json file and reclone the repo as a lot of changes have been made.

**Comment by McMelonTV** [comment]
now it just freezes like this 
![image](https://user-images.githubusercontent.com/62901799/151189507-b0c740db-9208-40a5-9700-be82fc765ca9.png)

**Comment by McMelonTV** [comment]
ig ima just use masscan but could you please format it's output like Qubo

**Comment by Pilot1782** [comment]
Sure I can add a formatting option for masscan to look like Qubo.

**Comment by McMelonTV** [comment]
> Sure I can add a formatting option for masscan to look like Qubo.

now if i use !mc with masscan it just doesn't even start scanning

**Comment by McMelonTV** [comment]
!cscan works tho
