### ISSUE TITLE
[Bug]: Full scan doesn't start

### ISSUE THREAD

**Issue by McMelonTV** [Pilot1782/bad_copenheimer#15]
### Contact Details

McMelon#9999 on Discord

### What happened?

A bug happened!

![image](https://user-images.githubusercontent.com/62901799/151050516-128c1507-737e-4ac2-bdd6-da0d88bb9588.png)

### Version

1.7 (Default)

### Relevant log output

```shell
Scanning on 10.0.0.0 through 199.255.255.255, with 8160 threads and timeout of 1
scanning using masscan
b'nmap(-oj): unknown output format\n'
Successfully appended 3 lines to the JSON file
```

**Comment by Pilot1782** [comment]
Can you show me the settings.json file

**Comment by McMelonTV** [comment]
![image](https://user-images.githubusercontent.com/62901799/151060348-15a47a40-e119-4fa3-b163-e2bc455b15d1.png)

**Comment by Pilot1782** [comment]
This error is caused by a typo on my part, a fix will be pushed soon.
