### ISSUE TITLE
[Bug]: Player not found in database

### ISSUE THREAD

**Issue by SusgUY446** [Pilot1782/bad_copenheimer#168]
### What happened?

When i use /find i get a the error 
Error
<username> not found in database

### Operating Sys

Windows

### Branch

- [ ] Tried `dev-builds`

### Relevant log output

```shell
Error
<username> not found in database
```

**Comment by Pilot1782** [comment]
The player is not in the database, try pinging a server that the player is playing on to add it into the db.
