### ISSUE TITLE
No module named 'funcs'

### ISSUE THREAD

**Issue by z0mbieslayer** [Pilot1782/bad_copenheimer#27]
I tried running the program today and I'm being met with this error. I went back a few commits to when you didn't utilize this module and it worked fine then, but I'd like to be able to use the most up to dat version possible. Any help would be great.

Output:
`Traceback (most recent call last):`
  `File "C:\Users\logan\Documents\bad_copenheimer\dis-bot.pyw", line 12, in <module>`
    `from funcs import *`
`ModuleNotFoundError: No module named 'funcs'`

**Comment by Pilot1782** [comment]
Ya so I made a new file called funds.pay on my local system it was excluded on the commits, I'll let you know when I add it, should be just a few min.

**Comment by Pilot1782** [comment]
ok funcs is added, you can either download funcs.py into your folder or reclone

**Comment by z0mbieslayer** [comment]
Thank you
