### ISSUE TITLE
Player searcher

### ISSUE THREAD

**Issue by Hamstergg10** [Pilot1782/bad_copenheimer#32]
It would be nice to search after players like in copenheimer.

An alternative is to print the playerlist in the logs.

**Comment by Pilot1782** [comment]
Hi, the current ways to implement such a module are as follows

## Method 1

Send custom packets,
this would include going through minecraft's server protocols and sending packets one by one to get a desired output, this would be slow and would not work for premium or non cracked servers.

## Method 2

Use a package for python,
this means using a package like [quarry](https://github.com/barneygale/quarry) to handle the packets and authentication for me.

## Method 3

Use an addon for [meteor-client](https://github.com/MeteorDevelopment/meteor-client),
that logs onto a server and grabs all players in the server.

## Method 4

Use a screen scrapper,
this would mean you need a dedicated computer and would act like a person that would, log onto a server, hold tab, take a screenshot, crop it to the player tab, and copy names to a text variable to be stored in a file


## Conclusion

The method I am currently looking to implement is Method 2, as it does not require a separate computer and has the advantages of raw packets without many of the drawbacks.
