### ISSUE TITLE
Hey pilot

### ISSUE THREAD

**Issue by Cabbasca** [Pilot1782/bad_copenheimer#37]
Server scanner project

**Comment by Cabbasca** [comment]
You wanna be part of our new scanner project?

**Comment by Cabbasca** [comment]
Whats your discord?

**Comment by Pilot1782** [comment]
Sure, Pilot1782#6718

**Comment by BookWyrm114** [comment]
Oooooohhhhh, this new server scanner project sounds awesome, congrats to pilot on getting asked to join what’s probably a private server scanner project! That’s really awesome!

**Comment by BloodyNoah** [comment]
Congrats I guess?

**Comment by Pilot1782** [comment]
Lol I'll see what it's about when I get an invite. I'm assuming it'll be a better clone of mcstalker

**Comment by BookWyrm114** [comment]
Hopefully, MCStalker was great, but had its issues, and now it’s gone ofc. Plus your an awesome dev, so it would be amazing to see what you could do for it

**Comment by Pilot1782** [comment]
Thanks, Im not a great dev, I just mash together boiler plate code and make slight edits until it works, or I make really bad functions that are unoptimizable such as the scan function in funcs.py

**Comment by Pilot1782** [comment]
I have been added, if you want to check my surrent status on this project see [here](https://github.com/users/Pilot1782/projects/1)
