### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Julian-of-Aland** [Pilot1782/bad_copenheimer#39]
### What happened?

Nothing! as son as a try to run it it fails and closes python.  if i use command line it just says no file found for setup or setup.py

C:\Users\me> python3 setup.py
python3: can't open file 'C:\\Users\\me\\setup.py': [Errno 2] No such file or directory

C:\Users\me>

### Version

1.7 (Default)

**Comment by Pilot1782** [comment]
The first thing I'm thinking is that the terminal is in the wrong directory, if the repo folder is not in C:\Users\me then in file explorer type cmd or powershell into the path or use cd [directory] to get there.
