### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yky4fan** [Pilot1782/bad_copenheimer#41]
### What happened?

when i run setup.py it displays an error message.

### Version

1.9.1 (Default)

### Relevant log output

```shell
C:\Users\yky4\Downloads\bad_copenheimer-main>python3 setup.py
Traceback (most recent call last):
  File "C:\Users\yky4\Downloads\bad_copenheimer-main\setup.py", line 3, in <module>
    from funcs import ptime
  File "C:\Users\yky4\Downloads\bad_copenheimer-main\funcs.py", line 9, in <module>
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
OSError: [Errno 22] Invalid argument: (it starts stating random files here including system32)
```

**Comment by Pilot1782** [comment]
This bug is caused when importing the timestamp function and tries to define a couple of local vars that have not been made and fails. This has been fixed in the new commit, you can download just the setup file or redownload.

**Comment by yky4fan** [comment]
C:\Users\yky4\Downloads\bad_copenheimer-main>python3 setup.py
'clear' is not recognized as an internal or external command,
operable program or batch file.

Is this being run on windows, or linux? windows
'clear' is not recognized as an internal or external command,
operable program or batch file.
C:\\Users\\yky4\\Downloads\\bad_copenheimer-main\\
Packages Already Imported, Exiting!
Updating file paths...
Traceback (most recent call last):
  File "C:\Users\yky4\Downloads\bad_copenheimer-main\setup.py", line 120, in <module>
    fix_files()
  File "C:\Users\yky4\Downloads\bad_copenheimer-main\setup.py", line 80, in fix_files
    replace_line(f"{inp}.env",1,r'PATH={}settings.json'.format(inp))
  File "C:\Users\yky4\Downloads\bad_copenheimer-main\setup.py", line 38, in replace_line
    lines[line_num] = text
IndexError: list assignment index out of range

(this is now whats showing in setup.py)

**Comment by Pilot1782** [comment]
got this fixed in the `dev-builds` branch
