### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hds1337** [Pilot1782/bad_copenheimer#42]
### What happened?

An error occured dispatching guild_application_command_index_update: module 'interactions' has no attribute 'GuildApplicationCommandIndex'

why is this happening

### Version

1.9.1 (Default)

### Relevant log output

```shell
An error occured dispatching guild_application_command_index_update: module 'interactions' has no attribute 'GuildApplicationCommandIndex'
```

**Comment by Pilot1782** [comment]
`pip install py-discord-interactions`
