### ISSUE TITLE
[Bug]: Dis-bot.pyw fails on run

### ISSUE THREAD

**Issue by timotiose** [Pilot1782/bad_copenheimer#45]
### Contact Details

timotiose@gmail.com

### What happened?

When i run dis-bot.py i get this error

PS C:\Users\me\Downloads\bad_copenheimer-dev-builds> python3 .\dis-bot.pyw
Traceback (most recent call last):
  File "C:\Users\me\Downloads\bad_copenheimer-dev-builds\dis-bot.pyw", line 8, in <module>
    from funcs import *
  File "C:\Users\me\Downloads\bad_copenheimer-dev-builds\funcs.py", line 10, in <module>
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
OSError: [Errno 22] Invalid argument: 'C:\\Program Files\\Microsoft MPI\\Bin\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ffmpeg\\bin;%PATH%;C:\\Program Files\\nodejs\\;C:\\Program Files\\PowerShell\\7\\;C:\\Ruby31-x64\\bin;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\;C:\\Users\\me\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\me\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\me\\AppData\\Roaming\\npm'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000187B4E62F20>

### Version

1.9.1 (Default)

### Relevant log output

```shell
PS C:\Users\me\Downloads\bad_copenheimer-dev-builds> python3 .\dis-bot.pyw
Traceback (most recent call last):
  File "C:\Users\me\Downloads\bad_copenheimer-dev-builds\dis-bot.pyw", line 8, in <module>
    from funcs import *
  File "C:\Users\me\Downloads\bad_copenheimer-dev-builds\funcs.py", line 10, in <module>
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
OSError: [Errno 22] Invalid argument: 'C:\\Program Files\\Microsoft MPI\\Bin\\;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ffmpeg\\bin;%PATH%;C:\\Program Files\\nodejs\\;C:\\Program Files\\PowerShell\\7\\;C:\\Ruby31-x64\\bin;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\;C:\\Users\\me\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\me\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\me\\AppData\\Roaming\\npm'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000187B4E62F20>
```

**Comment by Pilot1782** [comment]
fix pushed to `dev-builds` branch
