### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jackylacky161** [Pilot1782/bad_copenheimer#46]
### What happened?

So basically when I try to run Setup.py it opens and closes after 1 second.

{
  "TOKEN":"filled",
  "lower_ip_bound":"172.65.238.255",
  "upper_ip_bound":"172.65.240.255",
  "threads":1020,
  "timeout":6000,
  "os":1,
  "home-dir": "C:\Users\username\bad_copenheimer-main",
  "user":"Pilot1782",
  "password":"Password123",
  "guild-id": filled,
  "server":true,
  "server-port":"8080",
  "masscan":false,
  "time2":1000,
  "lin-py":"python3",
  "win-py":"%LOCALAPPDATA%\\Programs\\Python\\Python310\\python.exe",
  "debugging":true,
  "testing":true
}

### Version

1.9.1 (Default)

![image](https://user-images.githubusercontent.com/107464069/173530527-bbaeb468-a575-4bf1-aec4-863070da06c8.png)

**Comment by z0mbieslayer** [comment]
It tries to use your default path variable in the code. You have to change the variable to one that you make that points to your settings file. Probably something that should be addressed in a future update.

**Comment by jackylacky161** [comment]
> It tries to use your default path variable in the code. You have to change the variable to one that you make that points to your settings file. Probably something that should be addressed in a future update.

You mean home-dir?

**Comment by z0mbieslayer** [comment]
> > It tries to use your default path variable in the code. You have to change the variable to one that you make that points to your settings file. Probably something that should be addressed in a future update.
> 
> oh now im getting another error ![image](https://user-images.githubusercontent.com/107464069/174405373-410e35b3-4886-4a5f-8c64-f3a6fabc152b.png)

remove the "-" in the folder name, then reflect that change for the variable value.

**Comment by jackylacky161** [comment]
> > > It tries to use your default path variable in the code. You have to change the variable to one that you make that points to your settings file. Probably something that should be addressed in a future update.
> > 
> > 
> > oh now im getting another error ![image](https://user-images.githubusercontent.com/107464069/174405373-410e35b3-4886-4a5f-8c64-f3a6fabc152b.png)
> 
> remove the "-" in the folder name, then reflect that change for the variable value.

still same error
![image](https://user-images.githubusercontent.com/107464069/174407343-6486a0bf-4644-4e37-ab72-812f5398a7d4.png)

**Comment by z0mbieslayer** [comment]
just out of curiosity, what is settings_path set to in your file?

**Comment by jackylacky161** [comment]
/home/runner/bad_copenheimer/settings.json

> just out of curiosity, what is settings_path set to in your file?

**Comment by z0mbieslayer** [comment]
> /home/runner/bad_copenheimer/settings.json
> 
> > just out of curiosity, what is settings_path set to in your file?

so it looks like this?
`settings_path = os.getenv("/home/runner/bad_copenheimer/settings.json")`

**Comment by Pilot1782** [comment]
> It tries to use your default path variable in the code. You have to change the variable to one that you make that points to your settings file. Probably something that should be addressed in a future update.

Ok so what is happening here is that the .env variable `PATH` is not being defined and thus we are seeing the system variable value for `PATH`. Changing the variable in .env to `PATH="path to settings file"` will fix this.

**Comment by jackylacky161** [comment]
> > /home/runner/bad_copenheimer/settings.json
> > > just out of curiosity, what is settings_path set to in your file?
> 
> so it looks like this? `settings_path = os.getenv("/home/runner/bad_copenheimer/settings.json")`

yea

**Comment by jackylacky161** [comment]
> PATH="path to settings file"

![image](https://user-images.githubusercontent.com/107464069/174429380-eda196a0-173c-4cb8-ab0a-5c663bc4d908.png)
It should look like this?

**Comment by jackylacky161** [comment]
not solved but i give up

**Comment by Pilot1782** [comment]
Ya I don't blame you this problem is why I really hate windows sometimes, as relative paths are stupid hard to make.
