### ISSUE TITLE
[Bug]: Error when running dis-bot.pyw

### ISSUE THREAD

**Issue by z0mbieslayer** [Pilot1782/bad_copenheimer#48]
### Contact Details

thugstem54@gmail.com

### What happened?

So basically I tried to get this working again recently, and the bot almost started until I got this error. I have no idea what I'm looking at so maybe someone can help me here:

### Version

1.9.1 (Default)

### Relevant log output

`C:\Users\logan\bad_copenheimer>py dis-bot.pyw`
`Traceback (most recent call last):`
`  File "C:\Users\logan\bad_copenheimer\dis-bot.pyw", line 35, in <module>`
`    guildid = data["guild-id"]`
`KeyError: 'guild-id'`
`Unclosed client session`
`client_session: <aiohttp.client.ClientSession object at 0x00000115C9FA2F50>`
`Unclosed connector`
`connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000115CA301F00>, 403314.937)]']`
`connector: <aiohttp.connector.TCPConnector object at 0x00000115C9FA3670>`

**Comment by z0mbieslayer** [comment]
Small update: did a few modifications and now it seems to just not recognize the ip_upper_bound and ip_lower_bound variables. I have quadruple checked the spellings and there's nothing that could conceivably be wrong here, leaving me stuck again.

`C:\Users\logan\bad_copenheimer>py dis-bot.pyw
Traceback (most recent call last):
  File "C:\Users\logan\bad_copenheimer\dis-bot.pyw", line 96, in <module>
    async def server_scan(ctx: interactions.CommandContext, ip_lower_bound: str, ip_upper_bound: str):
  File "C:\Users\logan\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\client\bot.py", line 949, in decorator
    self.__check_command(
  File "C:\Users\logan\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\client\bot.py", line 848, in __check_command
    __check_options(_option, _opt_names)
  File "C:\Users\logan\AppData\Local\Programs\Python\Python310\lib\site-packages\interactions\client\bot.py", line 732, in __check_options
    raise InteractionException(
interactions.api.error.InteractionException: Error creating your command. The option name does not match the regex for valid names ('^[a-z0-9_-]1,32$') Error code: 11
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E0BB926F50>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001E0BBC820E0>, 159797.234)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001E0BB927670>`

**Comment by Pilot1782** [comment]
Here's what that error means:

# Line 96

`async def server_scan(ctx: interactions.CommandContext, ip_lower_bound: str, ip_upper_bound: str): `

The code here is creating a new asynchronous function named `server_scan`. The error is thrown there as the name is not a valid RegEx string. It may only contain: `^[a-z0-9_-]1,32$ `, here's the weird part, `server_scan` is valid. This is the current error on my build that I am debugging, once I find a fix I will push it to the `dev-builds` branch.

**Comment by z0mbieslayer** [comment]
Sweet, thanks for letting me know.

**Comment by timotiose** [comment]
![image](https://user-images.githubusercontent.com/57829932/175870023-1945b044-23a0-461c-bcdd-a46d4aa35c19.png)
Im assuming im not supposed to get this error

**Comment by Pilot1782** [comment]
> No, the fixed version is on the dev builds branch.

ok that version had some issues but it is fixed now

**Comment by Pilot1782** [comment]
The issues mentioned have been fixed in the latest main release.
