### ISSUE TITLE
[Bug]:  Setup.py , Os Error: 22

### ISSUE THREAD

**Issue by Phardeus** [Pilot1782/bad_copenheimer#50]
### What happened?

When i run Setup.py i get this out put :

`Traceback (most recent call last):
  File "C:\Users\(My Name)\Downloads\bad_copenheimer-dev-builds\setup.py", line 3, in <module>
    from funcs import ptime, dprint
  File "C:\Users\(My Name)\Downloads\bad_copenheimer-dev-builds\funcs.py", line 10, in <module>
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
OSError: [Errno 22] Invalid argument: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\Program Files\\AdoptOpenJDK\\bin;C:\\Program Files (x86)\\dotnet\\;C:\\Users\\(My Name)\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\luetk\\.dotnet\\tools`

My .env is :

`TOKEN=My Token
PATH=C:\\Users\\(My Name)\\Downloads\\bad_copenheimer\\
GUILDID=56789`

It looks like the problem in #33 but i´m using Windows 10 the other issue was under Linux.
Also #41 looks similar.
Is it possibil that it´s the same Problem, or culd i be the problem?
I´m using the dev-builds it looks like the same issue exists on the main branche.

### Version

1.9.1 (Default)

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\(My Name)\Downloads\bad_copenheimer-dev-builds\setup.py", line 3, in <module>
    from funcs import ptime, dprint
  File "C:\Users\(My Name)\Downloads\bad_copenheimer-dev-builds\funcs.py", line 10, in <module>
    with open(settings_path, "r") as read_file: # Open the settings file and start defineing variables from it
OSError: [Errno 22] Invalid argument: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\Program Files\\AdoptOpenJDK\\bin;C:\\Program Files (x86)\\dotnet\\;C:\\Users\\(My Name)\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\luetk\\.dotnet\\tools
```

**Comment by Pilot1782** [comment]
Ya I'm close to fixing this issue but it's difficult due to my bad implementation of `funcs.py`. The way I'm doing it is a class file with a path passed at init.

**Comment by Pilot1782** [comment]
As for fixing it, not much you can do but use the `1.9.1` Release.

**Comment by Phardeus** [comment]
Ok Thanks

**Comment by Pilot1782** [comment]
fix pushed to dev-builds
