### ISSUE TITLE
[Bug]: dis-bot.pyw

### ISSUE THREAD

**Issue by byronbonkers** [Pilot1782/bad_copenheimer#66]
### Contact Details

byronbonkers@gmail.com

### What happened?

I Have checked all of the .env and settings.json files repeatedly and still get this error:

### Version

1.9.1 (Default)

### Branch

main (Default)

### Relevant log output

```shell
pi@assistant:~/bad_copenheimer $ python3 dis-bot.pyw
Traceback (most recent call last):
  File "/home/pi/bad_copenheimer/dis-bot.pyw", line 17, in <module>
    fncs = funcs(settings_path)
  File "/home/pi/bad_copenheimer/funcs.py", line 15, in __init__
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xb59fa190>
```

**Comment by LiamTheNinja5** [comment]
I am having this same problom

**Comment by Pilot1782** [comment]
For now, in `did-bot.pyw` edit the line that says `settings_path = ...` to say `settings_path = "your path"`

**Comment by byronbonkers** [comment]
But after that I get this error
`Traceback (most recent call last):
  File "/home/pi/bad_copenheimer/dis-bot.pyw", line 17, in <module>
    fncs = funcs(settings_path)
  File "/home/pi/bad_copenheimer/funcs.py", line 19, in __init__
    data = json.load(read_file)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 3 (char 90)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xb59f3160>
`

**Comment by Pilot1782** [comment]
Make sure you have a comma at the end of line 4

`JSONDecodeError: Expecting ',' delimiter: line 4 column 3 (char 90) `

**Comment by byronbonkers** [comment]
ok

**Comment by byronbonkers** [comment]
Traceback (most recent call last):
  File "/home/pi/bad_copenheimer/dis-bot.pyw", line 17, in <module>
    fncs = funcs(settings_path)
  File "/home/pi/bad_copenheimer/funcs.py", line 15, in __init__
    with open(
TypeError: expected str, bytes or os.PathLike object, not tuple
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xb5a50190>

**Comment by Pilot1782** [comment]
Can you send me the json file contents?

**Comment by byronbonkers** [comment]
ok, no probs
`
{
  "TOKEN":"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&",
  "lower_ip_bound":"172.65.238.255",
  "upper_ip_bound":"172.65.240.255",
  "threads":1020,
  "timeout":6000,
  "os":"0"
  "home-dir": "/home/pi/bad_copenheimer/",
  "user":"resolver_cpp"
  "password":maus03maus03
  "guild-id": 1234,
  "server":false,
  "server-port":"8080",
  "masscan":false,
  "time2":1000,
  "lin-py":"python3",
  "win-py":"%LOCALAPPDATA%\\Programs\\Python\\Python310\\python.exe",
  "debugging":true,
  "testing":false
`

**Comment by Pilot1782** [comment]
Ok, try using this:

```
{
"TOKEN":"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&", "lower_ip_bound":"172.65.238.255", "upper_ip_bound":"172.65.240.255", "threads":1020,
"timeout":6000,
"os":0,
"home-dir": "/home/pi/bad_copenheimer/", "user":"REDACTED",
"password":"REDACTED",
"guild-id": 1234,
"server":false,
"server-port":"8080", "masscan":false,
"time2":1000,
"lin-py":"python3",
"win-py":"%LOCALAPPDATA%\\Programs\\Python\\Python310\\python.exe",
"debugging":true,
"testing":false
}
```

**Comment by byronbonkers** [comment]
It still says the same thing

**Comment by byronbonkers** [comment]
Traceback (most recent call last):
  File "/home/pi/bad_copenheimer/dis-bot.pyw", line 17, in <module>
    fncs = funcs(settings_path)
  File "/home/pi/bad_copenheimer/funcs.py", line 15, in __init__
    with open(
TypeError: expected str, bytes or os.PathLike object, not tuple
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xb5a19148>

**Comment by Pilot1782** [comment]
This should be fixed in the latest dev-builds push.
