### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by PilaCiu** [Pilot1782/bad_copenheimer#9]
I get these errors and I don't know how to fix them
![errors](https://user-images.githubusercontent.com/86489933/149376476-121f17de-032f-4f3d-b22f-bd08a0f7775e.PNG)

**Comment by Pilot1782** [comment]
Since you are on windows open the folder where the settings json file is located and right-click -> Properties then copy the path into the line that says 
>settings_path = r”PUT YOUR PATH HERE”

**Comment by Pilot1782** [comment]
In the settings.json file make sure that all lines end with a comma except the first and the last 2 lines ie:

>{
>  "token":"YOUR TOKEN HERE",
>  "lower_ip_bound":"10.0.0.0",
>  "upper_ip_bound":"199.255.255.255",
>  "threads":1020,
>  "timeout":1000,
>  "path":"qubo.jar",
>  "output-json":"outputs.json",
>  "os":1,
>  "os_comment":"1=Windows,0=Linux",
>  "mascan":"False",
>  "time2":1000000,
>  "name":"Pilot1782",
>  "password":"Password123",
>  "server":true,
>  "server-port":"8000",
>  "debugging":true
>}

**Comment by PilaCiu** [comment]
Thanks for help, that was the problem and I didn't realize, bot seems to be running perfectly now.
