### ISSUE TITLE
[Bug]: (Windows) Setup.py crashes

### ISSUE THREAD

**Issue by enzomtpYT** [Pilot1782/bad_copenheimer#90]
### What happened?

Hi ! I just tried to do `py setup.py` and this happened, (the clear error is bc clear doesn't exists on windows, its cls), but i don't know how to manually fix the next error, can you help me or even fix the error ?

Thank you in advance
Your Cordialities
-enzomtp

### Version

1.9.1 (Default)

### Branch

main (Default)

### Relevant log output

```shell
'clear' is not recognized as an internal or external command, executable program or batch file.
Packages Already Imported, Exiting!
Updating file paths...
Traceback (most recent call last):
  File "E:\IDM\Compressed\bad_copenheimer-main\setup.py", line 71, in <module>
    fix_files()
  File "E:\IDM\Compressed\bad_copenheimer-main\setup.py", line 59, in fix_files
    ast.literal_eval('replace_line(f"{inp}.env",0,r\'{}PATH={}settings.json{}'.format("\r",inp,"\n")) if inp("Do you want to use enviroment variables? (y/n) ").lower() == "y" else 'replace_line(f"{inp}dis-bot.pyw",11,r\'{}settings_path =\' "{}settings.json{}"'.format("\r",inp,"\n")
TypeError: 'str' object is not callable
```

**Comment by Pilot1782** [comment]
Please check the [troubleshooting](https://github.com/Pilot1782/bad_copenheimer/wiki/Troubleshooting) wiki page first and come back with any un solved issues.

**Comment by enzomtpYT** [comment]
After looking at the [troubleshooting](https://github.com/Pilot1782/bad_copenheimer/wiki/Troubleshooting) page, i didn't found anything helpfull, i also tried the dev branch i also didn't worked.

**Comment by Pilot1782** [comment]
Odd, both of these issues should be fixed in the dev-builds version of setup.py.

**Comment by Pilot1782** [comment]
Alright got a fix pushed to the dev-builds branch.

**Comment by Pilot1782** [comment]
Fixed in latest dev-builds push.
