### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by z0ren** [Pilot1782/bad_copenheimer#91]
### What happened?

Packages Already Imported, Exiting!
Updating file paths...
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    fix_files()
  File "setup.py", line 59, in fix_files
    ast.literal_eval('replace_line(f"{inp}.env",0,r\'{}PATH={}settings.json{}'.format("\r",inp,"\n")) if inp("Do you want to use enviroment variables? (y/n) ").lower() == "y" else 'replace_line(f"{inp}dis-bot.pyw",11,r\'{}settings_path =\' "{}settings.json{}"'.format("\r",inp,"\n")
TypeError: 'str' object is not callable

Trying to run setup.py, installed the requirements before running setup.

### Operating Sys

Linux

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
Packages Already Imported, Exiting!
Updating file paths...
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    fix_files()
  File "setup.py", line 59, in fix_files
    ast.literal_eval('replace_line(f"{inp}.env",0,r\'{}PATH={}settings.json{}'.format("\r",inp,"\n")) if inp("Do you want to use enviroment variables? (y/n) ").lower() == "y" else 'replace_line(f"{inp}dis-bot.pyw",11,r\'{}settings_path =\' "{}settings.json{}"'.format("\r",inp,"\n")
TypeError: 'str' object is not callable
```

**Comment by Pilot1782** [comment]
Please check the [troubleshooting](https://github.com/Pilot1782/bad_copenheimer/wiki/Troubleshooting) wiki page first and come back with any unsolved issues.

**Comment by Pilot1782** [comment]
Fixed in latest dev-builds push
